name: Desplegar a Repo Externo

on:
  push:
    branches:
      - main  # O 'master', la rama donde tienes tu código estable

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Bajamos el código del Repo A
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      # 2. Instalar Node + Configurar el registro de GitHub (MAGIA AQUÍ)
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 3. Instalar dependencias inyectando el Token
      - name: Instalar dependencias
        run: npm ci

      # 4. Construir proyecto (Build)
      - name: Construir proyecto (Build)
        run: npm run build
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          CONVEX_SELF_HOSTED_URL: ${{ secrets.CONVEX_SELF_HOSTED_URL }}
          CONVEX_SELF_HOSTED_ADMIN_KEY: ${{ secrets.CONVEX_SELF_HOSTED_ADMIN_KEY }}
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}

      # 4.1 Fix 404 for SPA
      - name: Fix 404 for SPA
        run: cp out/index.html out/404.html

      # 4.2 Evitar que Jekyll ignore archivos de Tailwind (_next)
      - name: Add .nojekyll
        run: touch out/.nojekyll

      # 4.3 Dominio Personalizado
      - name: Configurar Dominio Personalizado (CNAME)
        run: echo "dash.camarai.es" > out/CNAME

      # 5. Desplegar al Repositorio B
      - name: Desplegar al Repositorio B
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }} # Reutilizamos el token para subir
          folder: out
          repository-name: Camarai-official/dash.camarai.es
          branch: main
          clean: true
          single-commit: true
