name: Desplegar a Repo Externo

on:
  push:
    branches:
      - main  # O 'master', la rama donde tienes tu código estable

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Bajamos el código del Repo A
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      # 2. Instalar Node + Configurar el registro de GitHub (MAGIA AQUÍ)
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instalar dependencias inyectando el Token
      - name: Instalar dependencias
        run: npm i

      # 4. Construir proyecto (Build)
      - name: Construir proyecto (Build)
        run: npm run build

      # 4.1 Fix 404 for SPA
      - name: Fix 404 for SPA
        run: cp out/index.html out/404.html

      # 5. Desplegar al Repositorio B
      - name: Desplegar al Repositorio B
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }} # Reutilizamos el token para subir
          folder: out
          repository-name: Camarai-official/dash.camarai.es
          branch: main
          single-commit: true
