name: Desplegar a Repo Externo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Bajamos el código del Repo A
      - name: Checkout del código fuente
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          fetch-depth: 0

      # 2. Instalar pnpm
      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      # 3. Instalar Node
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      # 4. Instalar dependencias
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      # 5. Construir proyecto (Build)
      - name: Construir proyecto (Build)
        run: pnpm run build
        env:
          NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
          CONVEX_SELF_HOSTED_URL: ${{ secrets.CONVEX_SELF_HOSTED_URL }}
          CONVEX_SELF_HOSTED_ADMIN_KEY: ${{ secrets.CONVEX_SELF_HOSTED_ADMIN_KEY }}
          CONVEX_DEPLOYMENT: ${{ secrets.CONVEX_DEPLOYMENT }}

      # 6. Optimizaciones para GitHub Pages
      - name: Fix 404 for SPA
        run: cp out/index.html out/404.html

      - name: Add .nojekyll
        run: touch out/.nojekyll

      - name: Configurar Dominio Personalizado (CNAME)
        run: echo "dash.camarai.es" > out/CNAME

      - name: Eliminar workflows del output
        run: rm -rf out/.github

      # 7. Desplegar al Repositorio B
      - name: Desplegar al Repositorio B
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          folder: out
          repository-name: Camarai-official/dash.camarai.es
          branch: main
          clean: true
          single-commit: true
